# Generated by Django 4.1.3 on 2023-03-07 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
        ('courses', '0003_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='images',
            field=models.ManyToManyField(blank=True, to='uploads.labeledimage'),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
