# Generated by Django 4.1.3 on 2023-03-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_images_alter_course_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='images',
        ),
    ]
