# Generated by Django 4.1.3 on 2023-02-13 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='image_name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to=uploads.models.user_directory_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload',
                'ordering': ['-created_at'],
            },
        ),
    ]
