# Generated by Django 4.1.3 on 2023-02-11 00:28

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.FileField(upload_to=uploads.models.user_directory_path),
        ),
    ]
