# Generated by Django 4.1.3 on 2023-03-10 18:45

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeledimage',
            name='image',
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='json_file',
            field=models.FileField(upload_to=uploads.models.json_file_path),
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='thumbnail',
            field=models.ImageField(upload_to=uploads.models.thumbnail_path),
        ),
        migrations.AlterModelTable(
            name='labeledimage',
            table='labeled_image',
        ),
    ]
