# Generated by Django 4.1.3 on 2023-04-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_labeledimage_course_studentannotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentannotation',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
    ]
