name: GCP Deploy
on:
  push:
    branches:
      - production

jobs:
  deploy-app-engine:
    name: App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Initialize GCP Credentials
        run: |
          # This client-secret.json is converted by GCP_SA_KEY
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Publish app to Google App Engine
        run: gcloud -q app deploy app.yaml --promote
